---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
  when: ansible_os_family == 'Debian'
  become: yes

- name: Install general prerequisites
  ansible.builtin.package:
    name:
      - curl
      - git
      - jq
      - unzip
      - apt-transport-https
      - ca-certificates
      - software-properties-common
    state: present
  become: yes

- name: Install custom user-defined packages
  ansible.builtin.package:
    name: "{{ azure_devops_custom_packages }}"
    state: present
  become: yes
  when: azure_devops_custom_packages | length > 0

- name: Install dynamic toolset dependencies
  ansible.builtin.package:
    name: "{{ azure_devops_dependencies }}"
    state: present
  become: yes
  when: azure_devops_dependencies | length > 0
