---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
  when: ansible_os_family == 'Debian'
  become: yes

- name: Install common prerequisites
  ansible.builtin.package:
    name:
      - curl
      - git
      - jq
      - unzip
      - ca-certificates
    state: present
  become: yes

- name: Install Debian-specific prerequisites
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - software-properties-common
    state: present
  become: yes
  when: ansible_os_family == 'Debian'

- name: Install dynamic toolset dependencies
  ansible.builtin.package:
    name: "{{ azure_devops_dependencies }}"
    state: present
  become: yes
  when: azure_devops_dependencies is defined and azure_devops_dependencies | length > 0
