---
- name: Install .NET Core SDK (Debian/Ubuntu)
  ansible.builtin.apt:
    name: "dotnet-sdk-{{ item }}"
    state: present
  loop: "{{ tool.versions | default([]) }}"
  become: yes
  when: ansible_os_family == 'Debian'

- name: Install .NET Core SDK (RedHat/CentOS)
  ansible.builtin.yum:
    name: "dotnet-sdk-{{ item }}"
    state: present
  loop: "{{ tool.versions | default([]) }}"
  become: yes
  when: ansible_os_family == 'RedHat'
