---
- name: Install Java (Debian/Ubuntu)
  ansible.builtin.apt:
    name: "openjdk-{{ item }}-jdk"
    state: present
  loop: "{{ tool.versions | default([]) }}"
  become: yes
  when: ansible_os_family == 'Debian'

- name: Install Java (RedHat/CentOS)
  ansible.builtin.yum:
    name: "java-{{ item }}-openjdk-devel"
    state: present
  loop: "{{ tool.versions | default([]) }}"
  become: yes
  when: ansible_os_family == 'RedHat'
