---
- name: Add Ondrej PHP PPA (Debian/Ubuntu)
  ansible.builtin.apt_repository:
    repo: "ppa:ondrej/php"
    state: present
  become: yes
  when: ansible_os_family == 'Debian'

- name: Install PHP (Debian/Ubuntu)
  ansible.builtin.apt:
    name: 
      - "php{{ item }}"
      - "php{{ item }}-cli"
      - "php{{ item }}-curl"
      - "php{{ item }}-xml"
      - "php{{ item }}-mbstring"
    state: present
  loop: "{{ tool.versions | default([]) }}"
  become: yes
  when: ansible_os_family == 'Debian'

- name: Install PHP (RedHat/CentOS)
  ansible.builtin.yum:
    name: 
      - "php-{{ item }}*"
      - "php-cli-{{ item }}*"
      - "php-curl-{{ item }}*"
      - "php-xml-{{ item }}*"
      - "php-mbstring-{{ item }}*"
    state: present
  loop: "{{ tool.versions | default([]) }}"
  become: yes
  when: ansible_os_family == 'RedHat'
